//
// GitReposOwner.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GitReposOwner: Codable {

    public var login: String?

    public init(login: String? = nil) {
        self.login = login
    }


}
