//
// GitReposItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GitReposItem: Codable {

    public var name: String?
    public var _private: Bool?
    public var owner: GitReposOwner?
    public var htmlUrl: String?
    public var _description: String?
    public var fork: Bool?
    public var url: String?
    public var stargazersCount: Int?
    public var watchersCount: Int?
    public var language: String?
    public var forksCount: Int?
    public var allowForking: Bool?

    public init(name: String? = nil, _private: Bool? = nil, owner: GitReposOwner? = nil, htmlUrl: String? = nil, _description: String? = nil, fork: Bool? = nil, url: String? = nil, stargazersCount: Int? = nil, watchersCount: Int? = nil, language: String? = nil, forksCount: Int? = nil, allowForking: Bool? = nil) {
        self.name = name
        self._private = _private
        self.owner = owner
        self.htmlUrl = htmlUrl
        self._description = _description
        self.fork = fork
        self.url = url
        self.stargazersCount = stargazersCount
        self.watchersCount = watchersCount
        self.language = language
        self.forksCount = forksCount
        self.allowForking = allowForking
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case _private = "private"
        case owner
        case htmlUrl = "html_url"
        case _description = "description"
        case fork
        case url
        case stargazersCount = "stargazers_count"
        case watchersCount = "watchers_count"
        case language
        case forksCount = "forks_count"
        case allowForking = "allow_forking"
    }

}
