//
// GitSearchUserItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GitSearchUserItem: Codable {

    public var login: String?
    public var _id: Int64?
    public var nodeId: String?
    public var avatarUrl: String?
    public var gravatarId: String?
    public var url: String?
    public var htmlUrl: String?
    public var followersUrl: String?
    public var followingUrl: String?
    public var gistsUrl: String?
    public var starredUrl: String?
    public var subscriptionsUrl: String?
    public var organizationsUrl: String?
    public var reposUrl: String?
    public var eventsUrl: String?
    public var receivedEventsUrl: String?
    public var type: String?
    public var score: Decimal?
    public var siteAdmin: Bool?

    public init(login: String? = nil, _id: Int64? = nil, nodeId: String? = nil, avatarUrl: String? = nil, gravatarId: String? = nil, url: String? = nil, htmlUrl: String? = nil, followersUrl: String? = nil, followingUrl: String? = nil, gistsUrl: String? = nil, starredUrl: String? = nil, subscriptionsUrl: String? = nil, organizationsUrl: String? = nil, reposUrl: String? = nil, eventsUrl: String? = nil, receivedEventsUrl: String? = nil, type: String? = nil, score: Decimal? = nil, siteAdmin: Bool? = nil) {
        self.login = login
        self._id = _id
        self.nodeId = nodeId
        self.avatarUrl = avatarUrl
        self.gravatarId = gravatarId
        self.url = url
        self.htmlUrl = htmlUrl
        self.followersUrl = followersUrl
        self.followingUrl = followingUrl
        self.gistsUrl = gistsUrl
        self.starredUrl = starredUrl
        self.subscriptionsUrl = subscriptionsUrl
        self.organizationsUrl = organizationsUrl
        self.reposUrl = reposUrl
        self.eventsUrl = eventsUrl
        self.receivedEventsUrl = receivedEventsUrl
        self.type = type
        self.score = score
        self.siteAdmin = siteAdmin
    }

    public enum CodingKeys: String, CodingKey { 
        case login
        case _id = "id"
        case nodeId = "node_id"
        case avatarUrl = "avatar_url"
        case gravatarId = "gravatar_id"
        case url
        case htmlUrl = "html_url"
        case followersUrl = "followers_url"
        case followingUrl = "following_url"
        case gistsUrl = "gists_url"
        case starredUrl = "starred_url"
        case subscriptionsUrl = "subscriptions_url"
        case organizationsUrl = "organizations_url"
        case reposUrl = "repos_url"
        case eventsUrl = "events_url"
        case receivedEventsUrl = "received_events_url"
        case type
        case score
        case siteAdmin = "site_admin"
    }

}
