//
// GitUserInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GitUserInfo: Codable {

    public var login: String?
    public var _id: Int64?
    public var nodeId: String?
    public var avatarUrl: String?
    public var gravatarId: String?
    public var url: String?
    public var htmlUrl: String?
    public var reposUrl: String?
    public var name: String?
    public var company: String?
    public var location: String?
    public var email: String?
    public var bio: String?
    public var followers: Int?
    public var following: Int?

    public init(login: String? = nil, _id: Int64? = nil, nodeId: String? = nil, avatarUrl: String? = nil, gravatarId: String? = nil, url: String? = nil, htmlUrl: String? = nil, reposUrl: String? = nil, name: String? = nil, company: String? = nil, location: String? = nil, email: String? = nil, bio: String? = nil, followers: Int? = nil, following: Int? = nil) {
        self.login = login
        self._id = _id
        self.nodeId = nodeId
        self.avatarUrl = avatarUrl
        self.gravatarId = gravatarId
        self.url = url
        self.htmlUrl = htmlUrl
        self.reposUrl = reposUrl
        self.name = name
        self.company = company
        self.location = location
        self.email = email
        self.bio = bio
        self.followers = followers
        self.following = following
    }

    public enum CodingKeys: String, CodingKey { 
        case login
        case _id = "id"
        case nodeId = "node_id"
        case avatarUrl = "avatar_url"
        case gravatarId = "gravatar_id"
        case url
        case htmlUrl = "html_url"
        case reposUrl = "repos_url"
        case name
        case company
        case location
        case email
        case bio
        case followers
        case following
    }

}
